#!/usr/bin/env bash
set -euo pipefail
FORCE=
while getopts "fH:h" o; do case $o in
	f) FORCE=1 ;;
	H) HOME="$(realpath "$OPTARG")";;
	h | *) cat <<EOH
$0 [OPTS] [DIR...]
OPTS:
	-f	force overwrite
	-H<DIR>	non-\$HOME homedir
	-h	halp
EOH
	;;& h) exit 0 ;; *) exit 1;;
esac done
shift $((OPTIND-1))
if [ $# -eq 0 ]; then set .; fi
find "$@" -name .loc | while read -r loc; do
	# shellcheck disable=SC2094
	while read -r line; do
		to="$HOME/${line##* }"
		from="$(realpath "$(dirname "$loc")/$(cut -d' ' -f1 <<<"$line")")"
		if [ -e "$to" ] && [ -z "$FORCE" ]; then
			echo "error: $to already exists" >&2
			echo "to overwrite run with -f" >&2
			exit 1
		fi
		echo "$to -> $from"; mkdir -p "$(dirname "$to")"; ln -fns "$from" "$to"
	done <"$loc"
done
